#!/usr/bin/ash

run_hook() {
    echo "Plug in your key now if you want to use it"
    echo -n "enter key password followed by enter: "
    read -s PW
    ykchalresp "$PW" | tr -d '\n' > /crypto_keyfile.bin
    echo
    echo "you may unplug your key now"
}

